//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSetting
    {
        public int ApplicationSettingsID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public Nullable<double> AwardPointsThreshold { get; set; }
        public Nullable<double> AwardpointsDeduction { get; set; }
        public Nullable<double> PerKmAwardPoints { get; set; }
        public Nullable<double> PriorityAreaRange { get; set; }
        public Nullable<double> RequestSearchRange { get; set; }
        public Nullable<double> RequestWaitingTime { get; set; }
        public Nullable<double> RequestResponseTime { get; set; }
        public string ProfilePicture { get; set; }
        public string OriginalPicture { get; set; }
        public Nullable<int> Preference1Make { get; set; }
        public Nullable<double> Preference1Rating { get; set; }
        public string Preference1Distance { get; set; }
        public Nullable<int> Preference2Make { get; set; }
        public Nullable<double> Preference2Rating { get; set; }
        public string Preference2Distance { get; set; }
        public Nullable<int> Preference3Make { get; set; }
        public Nullable<double> Preference3Rating { get; set; }
        public string Preference3Distance { get; set; }
        public Nullable<int> ArrivedTime { get; set; }
        public string PaypalAccountNumber { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalNationalNumber { get; set; }
        public string PaypalCountryCode { get; set; }
        public string PaypalPhoneExt { get; set; }
        public Nullable<double> LaterBookingRequestSearchRange { get; set; }
        public Nullable<double> CaptainMinRating { get; set; }
        public Nullable<double> CaptainMinAcceptanceRate { get; set; }
        public Nullable<int> RequestRadiusInterval { get; set; }
        public Nullable<int> CaptainAllowedIdleTimeInSeconds { get; set; }
    }
}
