//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benificiary
    {
        public System.Guid BenificiaryID { get; set; }
        public System.Guid GuardianID { get; set; }
        public System.Guid ChildID { get; set; }
        public bool IsGuardianVerified { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
    }
}
