//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelReason
    {
        public int ID { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> isCaptainReleated { get; set; }
        public Nullable<bool> isLaterBookingReleated { get; set; }
        public Nullable<bool> isNormalBookingReleated { get; set; }
    }
}
