//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captain
    {
        public System.Guid CaptainID { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public Nullable<System.Guid> ResellerID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string Name { get; set; }
        public string OriginalLicense { get; set; }
        public string DrivingLicense { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<double> EarningPoints { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsPriorityHoursActive { get; set; }
        public string Email { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<int> TotalOnlineHours { get; set; }
        public string OriginalPicture { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> MemberSince { get; set; }
        public string ShareCode { get; set; }
        public Nullable<int> NumberOfFavoriteUser { get; set; }
        public Nullable<System.Guid> CaptainIDFK { get; set; }
        public string PaypalMerchantID { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalNationalNumber { get; set; }
        public string PaypalCountryCode { get; set; }
        public string PaypalPhoneExt { get; set; }
        public Nullable<double> Rating { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<System.DateTime> LastPriorityHourStartTime { get; set; }
        public Nullable<System.DateTime> LastPriorityHourEndTime { get; set; }
        public string LaterBookingNotificationTone { get; set; }
        public string NormalBookingNotificationTone { get; set; }
        public Nullable<int> NoOfTrips { get; set; }
        public Nullable<int> NoOfTripsMobilePay { get; set; }
        public Nullable<decimal> Earning { get; set; }
        public Nullable<decimal> MobilePayEarning { get; set; }
        public bool ShowOtherVehicles { get; set; }
        public Nullable<double> RideRadius { get; set; }
        public string Facilities { get; set; }
        public string Address { get; set; }
        public string HouseNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string TaxiLicense { get; set; }
        public string OriginalTaxiLicense { get; set; }
        public string IdentifiactionNumber { get; set; }
        public int NoOfRequestsReceived { get; set; }
        public Nullable<int> AcceptanceRate { get; set; }
    }
}
