//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public Nullable<System.Guid> ResellerID { get; set; }
        public string OwnerName { get; set; }
        public string ProfilePicture { get; set; }
        public string OriginalProfilePicture { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> isHotelSubscribed { get; set; }
        public Nullable<bool> isHotelActive { get; set; }
        public string HotelName { get; set; }
        public string HotelLogo { get; set; }
        public string OriginalHotelLogo { get; set; }
        public Nullable<System.DateTime> HotelSubscriptionDate { get; set; }
        public Nullable<System.DateTime> HotelExpiryDate { get; set; }
        public string HotelLatitude { get; set; }
        public string HotelLongitude { get; set; }
        public string HotelAddress { get; set; }
        public Nullable<bool> isHotelPrepaid { get; set; }
        public Nullable<System.DateTime> HotelDueDate { get; set; }
        public Nullable<int> HotelPaymentStatusID { get; set; }
        public Nullable<bool> isHotelPercentageBasedPayment { get; set; }
        public string HotelContractFile { get; set; }
        public string OriginalHotelContractFile { get; set; }
        public Nullable<decimal> HotelAmount { get; set; }
        public Nullable<int> HotelSubscriptionPlanID { get; set; }
        public Nullable<int> PaymentModeIDHotel { get; set; }
        public Nullable<int> HotelPreference1Make { get; set; }
        public Nullable<double> HotelPreference1Rating { get; set; }
        public string HotelPreference1Distance { get; set; }
        public Nullable<int> HotelPreference2Make { get; set; }
        public Nullable<double> HotelPreference2Rating { get; set; }
        public string HotelPreference2Distance { get; set; }
        public Nullable<int> HotelPreference3Make { get; set; }
        public Nullable<double> HotelPreference3Rating { get; set; }
        public string HotelPreference3Distance { get; set; }
        public Nullable<bool> isFleetSubscribed { get; set; }
        public Nullable<bool> isFleetActive { get; set; }
        public string FleetAddress { get; set; }
        public string FleetName { get; set; }
        public string FleetLogo { get; set; }
        public string OriginalFleetLogo { get; set; }
        public Nullable<System.DateTime> FleetSubscriptionDate { get; set; }
        public Nullable<System.DateTime> FleetExpiryDate { get; set; }
        public Nullable<bool> isFleetPrepaid { get; set; }
        public Nullable<System.DateTime> FleetDueDate { get; set; }
        public Nullable<int> FleetPaymentStatusID { get; set; }
        public Nullable<bool> isFleetPercentageBasedPayment { get; set; }
        public string FleetContractFile { get; set; }
        public string OriginalFleetContractFile { get; set; }
        public Nullable<decimal> FleetAmount { get; set; }
        public Nullable<int> FleetSubscriptionPlanID { get; set; }
        public Nullable<int> PaymentModeIDFleet { get; set; }
        public Nullable<bool> isCompanySubscribed { get; set; }
        public Nullable<bool> isCompanyActive { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string OriginalCompanyLogo { get; set; }
        public Nullable<System.DateTime> CompanySubscriptionDate { get; set; }
        public Nullable<System.DateTime> CompanyExpiryDate { get; set; }
        public string CompanyLatitude { get; set; }
        public string CompanyLongitude { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<bool> isCompanyPrepaid { get; set; }
        public Nullable<System.DateTime> CompanyDueDate { get; set; }
        public Nullable<int> CompanyPaymentStatusID { get; set; }
        public Nullable<bool> isCompanyPercentageBasedPayment { get; set; }
        public string CompanyContractFile { get; set; }
        public string OriginalCompanyContractFile { get; set; }
        public Nullable<decimal> CompanyAmount { get; set; }
        public Nullable<decimal> CompanyBalance { get; set; }
        public Nullable<int> CompanySubscriptionPlanID { get; set; }
        public string PaypalMerchantID { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalNationalNumber { get; set; }
        public string PaypalCountryCode { get; set; }
        public string PaypalPhoneExt { get; set; }
        public Nullable<int> PaymentModeIDCompany { get; set; }
        public string FleetATUNumber { get; set; }
        public string FleetIBAN { get; set; }
        public string FleetOriginalBusinessLicense { get; set; }
        public string FleetBusinessLicense { get; set; }
        public string FleetOriginalCommercialLegalGF { get; set; }
        public string FleetCommercialLegalGF { get; set; }
        public string FleetOriginalPowerOfAttorney { get; set; }
        public string FleetPowerOfAttorney { get; set; }
        public string FleetOriginalDeed { get; set; }
        public string FleetDeed { get; set; }
        public string FleetCity { get; set; }
        public string FleetPostalCode { get; set; }
        public string FleetBuildingNumber { get; set; }
        public int ReportsId { get; set; }
    }
}
