//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyVoucher
    {
        public System.Guid VoucherID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
