//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCoWorker
    {
        public System.Guid CoworkerID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<bool> IsCoworkerVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string VerificationCode { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
