//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponsManager
    {
        public System.Guid CouponID { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public bool isUsed { get; set; }
        public System.DateTime GeneratedOn { get; set; }
        public Nullable<System.DateTime> UsedOn { get; set; }
        public Nullable<System.Guid> UsedBy { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
