//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierServicesDistrict
    {
        public int DistrictID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string DistrictName { get; set; }
        public int Xindex { get; set; }
        public int Yindex { get; set; }
        public bool IsDistrictLabel { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime LastSubmitted { get; set; }
    }
}
