//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatcher
    {
        public System.Guid DispatchID { get; set; }
        public string WalkInCustomerName { get; set; }
        public string WalkInCustomerContactNumber { get; set; }
        public string WalkInCustomerPickLocationLatitude { get; set; }
        public string WalkInCustomerPickLocationLongitude { get; set; }
        public Nullable<double> MinimumDistance { get; set; }
        public Nullable<double> TargetSearchArea { get; set; }
        public Nullable<System.Guid> AssignedFromCaptainID { get; set; }
        public Nullable<System.Guid> AssignedToCaptainID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
    }
}
