//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatcherProfile
    {
        public System.Guid DispatchUserID { get; set; }
        public string Name { get; set; }
        public string ProfilePic { get; set; }
        public string OriginalPicture { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool isActive { get; set; }
        public string TotalOnlineHours { get; set; }
        public System.DateTime MemberSince { get; set; }
        public int TotalDispatchedRides { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
    }
}
