//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool isActive { get; set; }
        public int ApplicationUserTypeID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
