//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareManager
    {
        public System.Guid FareManagerID { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> BookingFare { get; set; }
        public Nullable<decimal> PerKmFare { get; set; }
        public Nullable<decimal> WaitingFare { get; set; }
        public string AreaLatLong { get; set; }
        public System.Guid ResellerID { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public System.Guid ApplicationID { get; set; }
        public Nullable<System.TimeSpan> EveningShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> EveningShiftEndTime { get; set; }
        public Nullable<decimal> EveningSurcharge { get; set; }
        public Nullable<decimal> EveningBaseFare { get; set; }
        public Nullable<decimal> EveningPerKmFare { get; set; }
        public Nullable<decimal> EveningPerMinFare { get; set; }
        public Nullable<System.TimeSpan> MorningShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> MorningShiftEndTime { get; set; }
        public Nullable<decimal> MorningSurcharge { get; set; }
        public Nullable<decimal> MorningBaseFare { get; set; }
        public Nullable<decimal> MorningPerKmFare { get; set; }
        public Nullable<decimal> MorningPerMinFare { get; set; }
    }
}
