//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareManagerLog
    {
        public System.Guid FareManagerLogID { get; set; }
        public Nullable<System.Guid> FareManagerID { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> BookingFare { get; set; }
        public Nullable<decimal> PerKmFare { get; set; }
        public Nullable<decimal> WaitingCharges { get; set; }
        public string AreaLatLong { get; set; }
        public System.Guid ResellerID { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public string Action { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
