//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareManagerTimeRanx
    {
        public System.Guid RangeID { get; set; }
        public string Range { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<System.Guid> FareManagerID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public bool isMorningShift { get; set; }
    }
}
