//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Go4SystemLocations
    {
        public System.Guid LocationID { get; set; }
        public System.Guid ResellerID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public string BuildingName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public string BuildingNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string OriginalDisplayImage { get; set; }
        public string DisplayImage { get; set; }
        public string Description { get; set; }
    }
}
