//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KarhooQuote
    {
        public string quote_id { get; set; }
        public Nullable<System.DateTime> date_scheduled { get; set; }
        public string account_id { get; set; }
        public int passenger_capacity { get; set; }
        public string PolyLine { get; set; }
        public Nullable<System.Guid> TripID { get; set; }
        public string PickupLocationLatitude { get; set; }
        public string PickupLocationLongitude { get; set; }
        public string PickUpLocation { get; set; }
        public string DropOffLocationLatitude { get; set; }
        public string DropOffLocationLongitude { get; set; }
        public string DropOffLocation { get; set; }
        public Nullable<System.Guid> PickUpFareManagerID { get; set; }
        public Nullable<System.Guid> DropOffFareMangerID { get; set; }
        public Nullable<int> InBoundDistanceInMeters { get; set; }
        public Nullable<int> InBoundTimeInSeconds { get; set; }
        public Nullable<decimal> InBoundTimeFare { get; set; }
        public Nullable<decimal> InBoundDistanceFare { get; set; }
        public Nullable<decimal> InBoundSurchargeAmount { get; set; }
        public Nullable<decimal> InBoundBaseFare { get; set; }
        public Nullable<int> OutBoundDistanceInMeters { get; set; }
        public Nullable<int> OutBoundTimeInSeconds { get; set; }
        public Nullable<decimal> OutBoundTimeFare { get; set; }
        public Nullable<decimal> OutBoundDistanceFare { get; set; }
        public Nullable<decimal> OutBoundSurchargeAmount { get; set; }
        public Nullable<decimal> OutBoundBaseFare { get; set; }
        public Nullable<System.DateTime> QuoteTimeStamp { get; set; }
        public string CaptainID { get; set; }
        public string CaptainLocationLatitude { get; set; }
        public string CaptainLocationLongitude { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string FlightNumber { get; set; }
        public string TrainNumber { get; set; }
        public string Comments { get; set; }
    }
}
