//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCaptainOnlineVehicle
    {
        public long ID { get; set; }
        public string CaptainID { get; set; }
        public string VehicleID { get; set; }
        public Nullable<System.DateTime> OnlineDateTime { get; set; }
        public Nullable<System.DateTime> OfflineDateTime { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
