//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerPlace
    {
        public int ID { get; set; }
        public int PlacesTypesID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitutde { get; set; }
        public string PassengerId { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
    }
}
