//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityHourLog
    {
        public System.Guid PriorityHourLogID { get; set; }
        public System.Guid CaptainID { get; set; }
        public System.DateTime PriorityHourStartTime { get; set; }
        public System.DateTime PriorityHourEndTime { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
