//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoManager
    {
        public System.Guid PromoID { get; set; }
        public string PromoCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> isFixed { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.Guid> ResellerID { get; set; }
        public Nullable<bool> isSpecialPromo { get; set; }
        public string PromotionName { get; set; }
        public string PickupLocation { get; set; }
        public string DropOffLocation { get; set; }
        public System.Guid ApplicationID { get; set; }
        public int Repetition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> WishCarAmount { get; set; }
    }
}
