//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsLog
    {
        public int ReportId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string ReportMonth { get; set; }
        public string Status { get; set; }
        public System.DateTime ProcessingStartDateTime { get; set; }
        public Nullable<System.DateTime> ProcessingEndDateTime { get; set; }
    }
}
