//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReroutedRidesLog
    {
        public System.Guid ReroutedLogID { get; set; }
        public System.Guid TripID { get; set; }
        public System.Guid CaptainID { get; set; }
        public System.DateTime LogTime { get; set; }
        public System.Guid ApplicationID { get; set; }
        public Nullable<int> CancelID { get; set; }
        public Nullable<System.DateTime> RideAcceptanceTime { get; set; }
        public bool isLaterBooking { get; set; }
    }
}
