//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardPointsManager
    {
        public int ID { get; set; }
        public int Deduction { get; set; }
        public int RedeemAmount { get; set; }
        public string Description { get; set; }
    }
}
