//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideServicesFareManager
    {
        public System.Guid RSFMID { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> BookingFare { get; set; }
        public Nullable<decimal> PerKmFare { get; set; }
        public Nullable<decimal> WaitingFare { get; set; }
        public System.Guid ResellerID { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public Nullable<System.TimeSpan> EveningShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> EveningShiftEndTime { get; set; }
        public Nullable<decimal> EveningSurcharge { get; set; }
        public Nullable<decimal> EveningBaseFare { get; set; }
        public Nullable<decimal> EveningPerKmFare { get; set; }
        public Nullable<decimal> EveningPerMinFare { get; set; }
        public Nullable<decimal> EveningBookingFare { get; set; }
        public Nullable<decimal> EveningWaitingFare { get; set; }
        public Nullable<System.TimeSpan> MorningShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> MorningShiftEndTime { get; set; }
        public Nullable<decimal> MorningSurcharge { get; set; }
        public Nullable<decimal> MorningBaseFare { get; set; }
        public Nullable<decimal> MorningPerKmFare { get; set; }
        public Nullable<decimal> MorningPerMinFare { get; set; }
        public Nullable<decimal> MorningBookingFare { get; set; }
        public Nullable<decimal> MorningWaitingFare { get; set; }
        public System.TimeSpan WeekendShiftStartTime { get; set; }
        public System.TimeSpan WeekendShiftEndTime { get; set; }
        public Nullable<decimal> WeekendSurcharge { get; set; }
        public Nullable<decimal> WeekendBaseFare { get; set; }
        public Nullable<decimal> WeekendPerKmFare { get; set; }
        public Nullable<decimal> WeekendPerMinFare { get; set; }
        public Nullable<decimal> WeekendBookingFare { get; set; }
        public Nullable<decimal> WeekendWaitingFare { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MorningWishCarRadius { get; set; }
        public decimal MorningWishCarExtraPrice { get; set; }
        public Nullable<int> EveningWishCarRadius { get; set; }
        public decimal EveningWishCarExtraPrice { get; set; }
        public Nullable<int> WeekendWishCarRadius { get; set; }
        public decimal WeekendWishCarExtraPrice { get; set; }
        public bool WeekendIsFixed { get; set; }
        public bool MorningIsFixed { get; set; }
        public bool EveningIsFixed { get; set; }
    }
}
