//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public System.Guid SettingsID { get; set; }
        public string PaypalAccountNumber { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalNationalNumber { get; set; }
        public string PaypalCountryCode { get; set; }
        public string PaypalPhoneExt { get; set; }
        public string CompanyLogo { get; set; }
        public string ProfileImage { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string OriginalCompanyLogo { get; set; }
        public string OriginalProfileImage { get; set; }
    }
}
