//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionHistory
    {
        public System.Guid SubsHistoryID { get; set; }
        public System.Guid SubscriberID { get; set; }
        public System.Guid SubscribeToID { get; set; }
        public int SubscriptionPlanID { get; set; }
        public int SubscriberTypeID { get; set; }
        public System.DateTime SubsDateTime { get; set; }
        public System.Guid TransactionID { get; set; }
    }
}
