//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public System.Guid DebitedFrom { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public System.Guid CreditedTo { get; set; }
        public string Reference { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public string PaypalId { get; set; }
        public string CreateTime { get; set; }
        public string UpdateTime { get; set; }
        public string FailureReason { get; set; }
        public string State { get; set; }
        public string Intent { get; set; }
        public string Cart { get; set; }
        public string Token { get; set; }
        public string NoteToPayer { get; set; }
        public string ExperienceProfileId { get; set; }
    }
}
