//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripRequestLog
    {
        public System.Guid RequestLogID { get; set; }
        public System.Guid TripID { get; set; }
        public System.Guid CaptainID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string CaptainLocationLatitude { get; set; }
        public string CaptainLocationLongitude { get; set; }
        public double DistanceToPickUpLocation { get; set; }
        public bool isReRouteRequest { get; set; }
    }
}
