//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReadNotification
    {
        public System.Guid Id { get; set; }
        public System.Guid FeedId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime ReadDateTime { get; set; }
    }
}
