//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvite
    {
        public System.Guid UserInvitesID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid ReferralID { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.Guid ApplicationID { get; set; }
        public bool IsReferredByDriver { get; set; }
    }
}
