//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public int ModelID { get; set; }
        public Nullable<int> MakeID { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public Nullable<System.Guid> ResellerID { get; set; }
        public bool isActive { get; set; }
    }
}
