//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public System.Guid VehicleID { get; set; }
        public string PlateNumber { get; set; }
        public string VehiclePicture { get; set; }
        public string OriginalVehiclePicture { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Color { get; set; }
        public bool isOccupied { get; set; }
        public Nullable<int> OccupiedBy { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.DateTime> LastDrove { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> TotalRides { get; set; }
        public Nullable<double> DistanceTravelled { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public Nullable<System.Guid> ResellerID { get; set; }
        public string Facilities { get; set; }
        public string RegistrationYear { get; set; }
        public string RegistrationCertificate { get; set; }
        public string OriginalRegistrationCertificate { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
