//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransfer
    {
        public System.Guid WalletTransferID { get; set; }
        public decimal Amount { get; set; }
        public System.Guid TransferredBy { get; set; }
        public System.Guid TransferredTo { get; set; }
        public string Referrence { get; set; }
        public System.DateTime RechargeDate { get; set; }
        public Nullable<System.Guid> TransacrionID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ResellerID { get; set; }
    }
}
